name: Update Detections and Send Email

on:
  schedule:
    - cron: '0 21 * * 1-5'  # Runs at 4 PM EST (21:00 UTC) Monday to Friday
  workflow_dispatch:

jobs:
  update-detections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y postfix mailutils

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Update Script
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          npm install axios nodemailer
          node update-detections.js

      - name: Display Update Summary
        run: cat update-summary.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add detections.json update-summary.txt
          git commit -m "🔄 Auto-update detections.json on $(date)" || echo "No changes to commit"
          git push origin main
