name: Update Detections and Send Email

on:
  schedule:
    - cron: '0 20 * * 1-5'  # Runs at 3 PM EST (20:00 UTC) Monday to Friday
  workflow_dispatch:  # Allows manual execution

jobs:
  update-detections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Update Script
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
        run: |
          npm install axios
          node update-detections.js

      - name: Send Email Notification via Sendmail
        if: always()
        run: |
          echo "Subject: 🚨 Detection Board Update: Summary Report" > email.txt
          echo "To: dan@cyflare.com" >> email.txt
          echo "From: GitHub Actions <github-actions@github.com>" >> email.txt
          echo "" >> email.txt
          cat update-summary.txt >> email.txt
          sendmail -t < email.txt
